function f(){this.g=!1;this.b=null;this.c=void 0;this.a=1;this.l=this.h=0;this.f=null}function n(a){if(a.g)throw new TypeError("Generator is already running");a.g=!0}f.prototype.i=function(a){this.c=a};function q(a,b){a.f={j:b,m:!0};a.a=a.h||a.l}f.prototype.return=function(a){this.f={return:a};this.a=this.l};function t(a,b,d){a.a=d;return{value:b}}function v(a){this.a=new f;this.b=a}
function w(a,b){n(a.a);var d=a.a.b;if(d)return x(a,"return"in d?d["return"]:function(h){return{value:h,done:!0}},b,a.a.return);a.a.return(b);return y(a)}function x(a,b,d,h){try{var e=b.call(a.a.b,d);if(!(e instanceof Object))throw new TypeError("Iterator result "+e+" is not an object");if(!e.done)return a.a.g=!1,e;var m=e.value}catch(l){return a.a.b=null,q(a.a,l),y(a)}a.a.b=null;h.call(a.a,m);return y(a)}
function y(a){for(;a.a.a;)try{var b=a.b(a.a);if(b)return a.a.g=!1,{value:b.value,done:!1}}catch(d){a.a.c=void 0,q(a.a,d)}a.a.g=!1;if(a.a.f){b=a.a.f;a.a.f=null;if(b.m)throw b.j;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function E(a){this.next=function(b){n(a.a);a.a.b?b=x(a,a.a.b.next,b,a.a.i):(a.a.i(b),b=y(a));return b};this.throw=function(b){n(a.a);a.a.b?b=x(a,a.a.b["throw"],b,a.a.i):(q(a.a,b),b=y(a));return b};this.return=function(b){return w(a,b)};this[Symbol.iterator]=function(){return this}}function F(a){function b(h){return a.next(h)}function d(h){return a.throw(h)}return new Promise(function(h,e){function m(l){l.done?h(l.value):Promise.resolve(l.value).then(b,d).then(m,e)}m(a.next())})}
var G="/ /favicon.ico /manifest.json /robots.txt /sitemap.xml /?utm_source=web_app_manifest /disclaimer/ /offline/ /privacy-policy/ /technical-information/ /terms-of-service/ /images/apple-touch-icon.png /images/favicon-32x32.png /images/favicon-16x16.png /images/feature-graphic-1024x500.jpg /images/logo-144x144.png /images/logo-192x192.png /images/logo-256x256.png /images/logo-384x384.png /images/logo-512x512-maskable.png /images/logo-512x512.png /images/logo.svg".split(" "),H=self;
H.addEventListener("install",function(a){a.waitUntil(H.caches.open("20210407-050428").then(function(b){b.addAll(G.map(function(d){return new Request(d,{mode:"no-cors"})})).catch(function(d){return console.log("Could not pre-cache resource:",d)})}).catch(function(b){return console.log("Could not pre-cache resources:",b)}))});H.addEventListener("message",function(a){a=a.data.action;var b={action:a};"getVersion"==a?b[a]="20210407-050428":"skipWaiting"==a&&H.skipWaiting();I(b)});
H.addEventListener("fetch",function(a){a.respondWith(H.caches.match(a.request).then(function(b){return b||J(a.request)}))});H.addEventListener("activate",function(a){I({event:a.type});a.waitUntil(K());L();return H.clients.claim()});function I(a){H.clients.matchAll().then(function(b){return b.forEach(function(d){d.postMessage(a)})})}function K(){return H.caches.keys().then(function(a){return Promise.all(a.map(function(b){if("20210407-050428"!==b)return H.caches.delete(b)}))})}
function L(){H.registration.addEventListener("updatefound",function(a){var b=H.registration.installing;b.addEventListener("statechange",function(d){"installed"==b.state&&(b.postMessage({action:"skipWaiting"}),I({event:d.type,action:"refresh"}))});I({event:a.type})})}
function J(a){var b,d,h,e,m,l,z,A,B,C;return F(new E(new v(function(c){switch(c.a){case 1:b=-1!=a.url.indexOf("&jsonp=");d={mode:b?"cors":"no-cors",credentials:b?"omit":"include"};if(b){var g={};for(var k=a.url.split("?").pop().split("&"),u=k.length>>>0;u--;){var r=k[u].split("="),p=r[0];p&&(g[p]=decodeURIComponent(r[1]))}k=g.query;u=k.length;for(var D=p=r=0;D<u;)r^=k.charCodeAt(D++)<<p,p+=8,p%=24;k=[g.action,r.toString(36).toUpperCase()];g.source&&k.push(g.source);g="offline-"+k.join("-")+".json"}else g=
"";h=g;c.h=2;return t(c,fetch(a,d),4);case 4:e=c.c;k=a.url;g=0==k.indexOf(H.location.origin);k=-1!=k.indexOf("nocache");if(("GET"!=a.method||!g||k)&&!b){c.a=5;break}return t(c,H.caches.open("20210407-050428"),6);case 6:m=c.c;if(!h){m.put(a,e.clone());c.a=5;break}console.log("request:",a);console.log("response:",e);if(!e.ok){c.a=5;break}return t(c,e.text(),9);case 9:l=c.c,z=(l||"").replace(/jsonp_\w+\(/,"jsonp_cb("),A=new Blob([z],{type:"application/json"}),console.log(h,l,z,A),m.put(h,new Response(A,
{status:304,statusText:"Not Modified",headers:e.headers}));case 5:c.a=3;c.h=0;break;case 2:return c.h=0,g=c.f.j,c.f=null,B=g,console.log("Could not fetch request:",B),t(c,H.caches.open("20210407-050428"),10);case 10:return C=c.c,b?(g=a.url.split("&jsonp=").pop().split("&")[0],g=fetch(new Request("data:text/javascript,"+g+"([])")),c=t(c,g,14)):c=t(c,C.match("/offline/"),13),c;case 13:e=c.c;c.a=12;break;case 14:e=c.c;case 12:console.log("Offline response:",e);case 3:return c.return(e)}})))};
